name: Daily Job Ingestion

on:
  schedule:
    # Run at 8:00 AM ET (12:00 UTC) daily
    - cron: '0 12 * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  ingest-jobs:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run remote jobs pipeline
      env:
        OPENAI__API_KEY: ${{ secrets.OPENAI_API_KEY }}
        DESTINATION__MOTHERDUCK__CREDENTIALS: ${{ secrets.MOTHERDUCK_CREDENTIALS }}
        RSS__REMOTE_FEED_URL: ${{ secrets.REMOTE_FEED_URL }}
        OPENAI__VECTOR_STORE_ID: ${{ secrets.OPENAI_VECTOR_STORE_ID }}
      run: |
        echo "Running remote jobs pipeline..."
        python -m pipelines.remote_jobs_pipeline
        
    - name: Run atlanta jobs pipeline  
      env:
        OPENAI__API_KEY: ${{ secrets.OPENAI__API_KEY }}
        DESTINATION__MOTHERDUCK__CREDENTIALS: ${{ secrets.DESTINATION__MOTHERDUCK__CREDENTIALS }}
        RSS__ATLANTA_FEED_URL: ${{ secrets.RSS__ATLANTA_FEED_URL }}
        OPENAI__VECTOR_STORE_ID: ${{ secrets.OPENAI__VECTOR_STORE_ID }}
      run: |
        echo "Running atlanta jobs pipeline..."
        python -m pipelines.atlanta_jobs_pipeline
        
    - name: Report completion
      run: |
        echo "✅ Both ingest pipelines completed successfully"